feat: add passmenu script with cliphist integration

diff --git a/.local/bin/passmenu b/.local/bin/passmenu
--- a/.local/bin/passmenu
+++ b/.local/bin/passmenu
@@ -2,37 +2,64 @@
 
 shopt -s nullglob globstar
 
+die() {
+	echo "$@" >&2
+	exit 1
+}
+
+clip() {
+	if [[ -n $WAYLAND_DISPLAY ]] && command -v wl-copy &> /dev/null; then
+		local copy_cmd=( wl-copy )
+		local paste_cmd=( wl-paste -n )
+		if [[ $PASSWORD_STORE_X_SELECTION == primary ]]; then
+			copy_cmd+=( --primary )
+			paste_cmd+=( --primary )
+		fi
+		local display_name="$WAYLAND_DISPLAY"
+	else
+		die "Error: No Wayland display or clipper detected"
+	fi
+	local sleep_argv0="password store sleep on display $display_name"
+
+	pkill -f "^$sleep_argv0" 2>/dev/null && sleep 0.5
+	local before="$("${paste_cmd[@]}" 2>/dev/null | base64)"
+	echo -n "$1" | "${copy_cmd[@]}" || die "Error: Could not copy data to the clipboard"
+	(
+		( exec -a "$sleep_argv0" bash <<<"trap 'kill %1' TERM; sleep '${PASSWORD_STORE_CLIP_TIME:-45}' & wait" )
+		local now="$("${paste_cmd[@]}" | base64)"
+		[[ $now != $(echo -n "$1" | base64) ]] && before="$now"
+
+		if command -v cliphist &>/dev/null; then
+			cliphist list | P="$1" awk 'substr($0, index($0, "\t") + 1) == ENVIRON["P"]' | cliphist delete
+		fi
+
+		echo "$before" | base64 -d | "${copy_cmd[@]}"
+	) >/dev/null 2>&1 & disown
+	echo "Copied $2 to clipboard. Will clear in ${PASSWORD_STORE_CLIP_TIME:-45} seconds."
+}
+
+typeit=0
 if [[ $1 == "--type" ]]; then
 	typeit=1
 	shift
 fi
 
-prefix=$PASSWORD_STORE_DIR
+prefix=${PASSWORD_STORE_DIR:-$HOME/.password-store}
 password_files=( "$prefix"/**/*.gpg )
 password_files=( "${password_files[@]#"$prefix"/}" )
 password_files=( "${password_files[@]%.gpg}" )
 
-choice=$(printf '%s\n' "${password_files[@]}" | mew -l 6 -p "$(basename $0)" -i "$@")
-[[ -n $choice ]] || exit
+password=$(printf '%s\n' "${password_files[@]}" | mew "$@")
 
-decrypted_pass=$(gpg --decrypt "$prefix/$choice.gpg" 2>/dev/null | head -n 1)
-[[ -n $decrypted_pass ]] || exit
+[[ -n $password ]] || exit
 
-full_content=$(gpg --decrypt "$prefix/$choice.gpg" 2>/dev/null)
-
-[[ -n $full_content ]] || exit 1
-
-if echo "$full_content" | grep -q "otpauth://"; then
-    decrypted_pass=$(echo "$full_content" | pass otp "$choice")
-else
-    decrypted_pass=$(echo "$full_content" | head -n 1)
+pass_cmd=show
+if pass show "$password" | grep -q '^otpauth://'; then
+	pass_cmd=otp
 fi
 
-[[ -n $decrypted_pass ]] || exit
-
-
 if [[ $typeit -eq 0 ]]; then
-	printf %s "$decrypted_pass" | wl-copy
+    clip "$(pass $pass_cmd "$password")" "$password"
 else
-	printf %s "$decrypted_pass" | wtype -
+	pass $pass_cmd "$password" | { IFS= read -r pass; printf %s "$pass"; } | wtype -
 fi
